/** English copy for the bilingual Dandelion concept. Russian is the source language. */
export const EN: Record<string, string> = {
"Концепт сайта туристического агентства, созданный как проект. Туры, цены, отзывы и формы на сайте используются только для демонстрации интерфейса.": "A travel agency website concept. Tours, prices, reviews and forms are for interface demonstration only.",
"Расскажите, каким вы представляете свой отпуск. В демонстрационной форме можно проверить валидацию и сценарий отправки.": "Tell us about your ideal holiday. Try the demo form to see validation and the submission flow.",
"во время путешествия": "during the trip",
"Открыть тур": "Open tour",
"Ознакомьтесь с направлениями путешествий Dandelion.": "Explore Dandelion travel destinations.",
"Подробная программа тура в Кению на 8 дней: Маасаи-Мара, Амбосели и пляжи Диани.": "Eight-day Kenya itinerary: Maasai Mara, Amboseli and Diani Beach.",
"8 дней сафари, лоджей и отдыха на берегу Индийского океана.": "Eight days of safari, lodges and Indian Ocean relaxation.",
"Демонстрационный туристический сайт: каталог, фильтры, страницы туров и формы.": "Travel website concept with tour listings, filters, detailed pages and forms.",
"Dandelion — демонстрационный проект туристического сайта.": "Dandelion — a travel website concept.",
"Демонстрационный туристический сайт с каталогом, фильтрами и страницами туров.": "A travel website concept with listings, filters and tour pages.",
"Dandelion — концепт сайта туристического агентства": "Dandelion — travel agency website concept",
"Dandelion — демонстрационный проект туристического сайта с каталогом туров и индивидуальным подбором.": "Dandelion — travel website concept with tour listings and custom trip planning.",
"Найти тур":"Find a tour","Готовые туры":"Our tours","Истории":"Stories","Индивидуальный тур":"Custom trip","Подобрать тур":"Plan a trip","Открыть меню":"Open menu","Закрыть меню":"Close menu","Основная навигация":"Main navigation","Мобильная навигация":"Mobile navigation","Dandelion — на главную":"Dandelion — home",
"Горячее предложение · осталось 5 мест":"Special offer · only 5 places left","Кения: сафари,":"Kenya: the safari","о котором вы":"you have always","мечтали":"dreamed of","8 дней от красных закатов Маасаи-Мара до белого песка пляжа Диани. Вылет из Тель-Авива 14 октября с пересадкой.":"8 days from the red sunsets of Maasai Mara to the white sands of Diani Beach. Departing Tel Aviv on October 14 with a connection.","Смотреть предложение":"Explore this trip",
"Куда отправимся":"Where to next?","Найдите своё путешествие":"Find your next adventure","Страна":"Country","Месяц":"Month","Бюджет на человека":"Budget per person","Бюджет":"Budget","Найти":"Search","Все страны":"All countries","Любой месяц":"Any month","Любой бюджет":"Any budget","до $2 000":"under $2,000","от $2 000":"over $2,000",
"Готовые путешествия":"Curated journeys","Выбирайте настроение":"Choose your adventure","Все цены и программы в этом проекте демонстрационные.":"All prices and itineraries shown are illustrative.","от":"from","/чел.":"/person","Подробнее":"Explore","По этим параметрам туров пока нет":"No tours match these filters","Сбросьте фильтры или оставьте заявку на индивидуальный подбор.":"Clear your filters or request a custom itinerary.","Показать все туры":"Show all tours",
"Истории путешественников":"Traveler stories","Истории, которые остаются с нами":"Stories that stay with us","Персонажи и отзывы созданы для демонстрации дизайна проекта.":"Characters and reviews are fictional and created for this concept.",
"Маршрут только для вас":"A journey made for you","Не нашли подходящий тур?":"Haven't found your perfect trip?","Любая точка мира":"Anywhere in the world","Для двоих, семьи или компании":"For couples, families or groups","Маршрут с нуля или адаптация готового":"A tailor-made route or a customized itinerary",
"Спасибо!":"Thank you!","Форма успешно отправлена.":"Form submitted successfully.","Это демонстрационная версия сайта. Введённые данные не сохраняются.":"This is a demo. Your details are not stored.","Заполнить ещё раз":"Fill out another form","Выбранный тур:":"Selected tour:","Ваше имя":"Your name","Телефон":"Phone","Куда хотите поехать":"Where would you like to go","Куда хотите поехать?":"Where would you like to go?","Пожелания к туру":"Trip preferences","Кто едет, примерные даты и пожелания":"Travelers, approximate dates and preferences","Демонстрационная форма. Введённые данные не сохраняются и никуда не отправляются.":"Demo form. Your information is neither saved nor sent.","Обсудить путешествие":"Plan my trip","Введите имя":"Please enter your name","Введите корректный номер телефона":"Enter a valid phone number","Максимум 100 символов":"Maximum 100 characters","Максимум 500 символов":"Maximum 500 characters",
"На главную":"Back to home","К турам":"Back to tours","К каталогу":"Browse tours","Тур не найден":"Tour not found","Страница не найдена":"Page not found","Возможно, страница была удалена или её адрес изменился.":"This page may have been removed or its address changed.","Не удалось загрузить страницу":"Unable to load page","Что-то пошло не так. Попробуйте обновить страницу или вернуться на главную.":"Something went wrong. Please refresh or return home.","Попробовать снова":"Try again",
"Ориентировочная стоимость":"Estimated price","Оставить заявку":"Send an inquiry","О путешествии":"About this journey","Главное":"Highlights","День за днём":"Day by day","Маршрут путешествия":"Your itinerary","Включено":"Included","Всё основное уже в маршруте":"The essentials are taken care of","Путь к путешествию":"Getting there","Из Израиля":"From Israel","Цена и программа — демонстрационные. Рейсы, даты, условия въезда и окончательную стоимость необходимо подтвердить перед бронированием.":"Prices and itineraries are illustrative. Confirm flights, dates, entry requirements and final prices before booking.","Обсудим поездку?":"Let's plan your trip","Заполните демонстрационную форму, чтобы увидеть сценарий заявки. Данные не сохраняются и не отправляются.":"Try the demo inquiry form. Your information is not saved or sent.",
"Горячее предложение · 14 октября 2026":"Special offer · October 14, 2026","Кения: сафари и океан":"Kenya: safari and ocean","Восемь дней среди саванны, слонов у подножия Килиманджаро и белых пляжей Индийского океана.":"Eight days of savannah, elephants beneath Kilimanjaro and white Indian Ocean beaches.","8 дней":"8 days","до 8 человек":"up to 8 guests","3 региона":"3 regions","Стоимость":"Price","ориентировочная стоимость":"estimated price","Вылет":"Departure","14 октября":"October 14","из Тель-Авива, с пересадкой":"from Tel Aviv, connecting flight","Свободно":"Availability","5 мест":"5 places","Для въезда в Кению по израильскому паспорту требуется электронное разрешение eTA. Перелёт из Тель-Авива — с пересадкой; расписание, возможность оформления и итоговую стоимость уточняйте перед бронированием.":"Israeli passport holders need a Kenya eTA. Flights from Tel Aviv connect en route; verify schedules, entry requirements and final pricing before booking.","Без скрытых сюрпризов":"No hidden surprises","Что входит в стоимость":"What's included","Отдельно оплачиваются электронная виза, личные расходы и дополнительные экскурсии по желанию.":"Entry authorization, personal expenses and optional excursions are not included.","Кения в кадре":"Kenya in pictures","От саванны до океана":"From savannah to sea","Три настроения одного путешествия: дикая природа Амбосели, золотой свет Маасаи-Мара и спокойный берег Диани.":"Three sides of Kenya: Amboseli's wildlife, the golden light of Maasai Mara and the peaceful Diani coast.","Слоны в Амбосели":"Elephants in Amboseli","Закат в Маасаи-Мара":"Sunset in Maasai Mara","Пляж Диани":"Diani Beach","Демонстрация формы":"Demo inquiry","Хочу в Кению":"Take me to Kenya","Проверьте сценарий заявки: данные валидируются, но не сохраняются и не отправляются.":"Try the inquiry form: fields are validated, but no information is stored or sent.",
"День 1":"Day 1","Дни 2–4":"Days 2–4","Дни 5–6":"Days 5–6","Дни 7–8":"Days 7–8","Перелёт и Наироби":"Arrival in Nairobi","Маасаи-Мара":"Maasai Mara","Амбосели":"Amboseli","Встреча в аэропорту, трансфер в бутик-отель и спокойный вечер после дороги.":"Airport welcome, transfer to a boutique hotel and a relaxed evening after your flight.","Перелёт в саванну, утренние и вечерние сафари, Большая пятёрка и ужины у костра.":"Fly into the savannah for morning and evening game drives, Big Five sightings and campfire dinners.","Слоны на фоне Килиманджаро, открытые джипы и ночь в лодже среди дикой природы.":"Elephants against Kilimanjaro, open-top game drives and a night at a wilderness lodge.","Белый песок, Индийский океан, свободный день и возвращение домой.":"White sands, the Indian Ocean, a free day and the journey home.","Международный и внутренние перелёты":"International and domestic flights","Проживание в лоджах 4–5★":"4–5★ lodge accommodation","Все сафари на открытых джипах":"All safaris in open-top vehicles","Полный пансион во время сафари":"Full board during safaris","Русскоговорящий сопровождающий":"Russian-speaking tour escort","Медицинская страховка":"Medical insurance",
"Дни 1–4":"Days 1–4","Сафари и знакомство с природой Кении.":"Safari and Kenya’s wild landscapes.","Слоны и виды на Килиманджаро.":"Elephants and views of Kilimanjaro.","Диани":"Diani","Белый песок и Индийский океан.":"White sand and the Indian Ocean.","Сафари":"Safari","Питание во время сафари":"Meals during safari","Сопровождение":"Tour escort","Страховка":"Insurance","Наверх ↑":"Back to top ↑","Концепт сайта туристического агентства, созданный как проект. Туры, цены,":"A travel agency website concept. Tours, prices,","отзывы и формы на сайте используются только для демонстрации интерфейса.":"reviews and forms are used for interface demonstration only.","Кения":"Kenya","Кипр":"Cyprus","Греция":"Greece","Япония":"Japan","Италия":"Italy","Грузия":"Georgia","Октябрь":"October","Ноябрь":"November","Декабрь":"December","7 ночей":"7 nights","8 ночей":"8 nights","10 дней":"10 days","Отель 4★":"4★ hotel","Отели 4★":"4★ hotels","Отель у моря 5★":"5★ seaside hotel","Бутик-отель 4★":"4★ boutique hotel","Лоджи 4–5★":"4–5★ lodges","Горячее предложение":"Special offer","Авторский выбор":"Editor's pick","Для двоих":"For two","Малая группа":"Small group","Средиземноморье":"Mediterranean","Горы и гастрономия":"Mountains & cuisine",
"Сафари и океан":"Safari and ocean","Море и легенды Пафоса":"Sea and legends of Paphos","Острова и солнце Эгейского моря":"Islands and Aegean sunshine","Осенний Киото":"Autumn in Kyoto","Амальфитанское побережье":"Amalfi Coast","Тбилиси и Кавказские горы":"Tbilisi and the Caucasus","Сафари в Маасаи-Мара":"Safari in Maasai Mara","Отдых на пляже Диани":"Relax on Diani Beach",
"Дни 1–2":"Days 1–2","Дни 3–4":"Days 3–4","Дни 5–7":"Days 5–7","Дни 1–3":"Days 1–3","Дни 3–5":"Days 3–5","Дни 4–7":"Days 4–7","Дни 6–8":"Days 6–8","Дни 8–10":"Days 8–10","Дни 6–7":"Days 6–7","Пафос":"Paphos","Акамас":"Akamas","Средиземное море":"Mediterranean Sea","Афины":"Athens","Островная Греция":"Greek islands","Море и свобода":"Sea and freedom","Токио":"Tokyo","Киото":"Kyoto","Арасияма и финал":"Arashiyama and farewell","Неаполь и побережье":"Naples and the coast","Амальфи и Позитано":"Amalfi and Positano","Свободная Италия":"Italy at your own pace","Тбилиси":"Tbilisi","Военно-Грузинская дорога":"Georgian Military Highway","Вино и свободный день":"Wine and leisure",
"Саванна, слоны у подножия Килиманджаро и тёплый океан в одном путешествии.":"Savannah, elephants beneath Kilimanjaro and the warm ocean in one journey.","Лазурные бухты, античные мозаики и вечера у Средиземного моря.":"Azure bays, ancient mosaics and Mediterranean evenings.","Белые улочки, тихие пляжи и время, которое принадлежит только вам.":"Whitewashed streets, quiet beaches and time that's entirely yours.","Клёны, храмы и тихие улочки в самое красивое время японской осени.":"Maple trees, temples and peaceful streets at the height of Japanese autumn.","Дороги над морем, лимонные сады и неспешные итальянские вечера.":"Coastal roads, lemon groves and leisurely Italian evenings.","Старинный Тбилиси, горные дороги и гостеприимство за большим столом.":"Old Tbilisi, mountain roads and warm Georgian hospitality.",
"Открыть тур:":"Open tour:","Саванна Кении на закате":"Kenyan savannah at sunset"
};

Object.assign(EN, {
"Расскажите, каким вы представляете свой отпуск. В демонстрационной форме можно проверить валидацию и сценарий отправки.": "Tell us what your ideal getaway looks like. This demo form lets you try validation and submission.",
"Концепт сайта туристического агентства, созданный как проект. Туры, цены, отзывы и формы на сайте используются только для демонстрации интерфейса.": "A travel agency website concept. Tours, prices, reviews and forms are for interface demonstration only.",
"Кения · сентябрь · групповой тур": "Kenya · September · group tour", "Париж · май · группа из 8 человек": "Paris · May · group of eight", "Италия · индивидуальный тур": "Italy · private trip", "Даниэль Окойо": "Daniel Okoye", "Анна Власова": "Anna Vlasova", "Виктор и Лидия Соколовы": "Victor and Lydia Sokolov",
"Я давно мечтал увидеть Кению — родину моего дедушки. Эта поездка стала очень личной: сафари, новые друзья и чувство, будто я наконец прикоснулся к истории семьи.": "I'd always dreamed of seeing Kenya, my grandfather's homeland. The safari, new friendships and a sense of reconnecting with my family's history made this trip unforgettable.",
"Париж был моей мечтой, и в мае она осуществилась. Нас было всего восемь — достаточно, чтобы найти друзей, и достаточно мало, чтобы почувствовать настоящий ритм города.": "Paris was my dream, and it finally came true in May. There were only eight of us: enough to make friends and few enough to feel the city's real rhythm.",
"Дети подарили нам Италию на золотую свадьбу — 50 лет вместе. Маршрут был только для нас, спокойный и очень душевный.": "Our children gave us a trip to Italy for our golden wedding anniversary — 50 years together. The itinerary was just for us, peaceful and heartfelt.",
"Сафари, простор саванны и несколько спокойных дней на Индийском океане в одном маршруте.": "Safari, vast savannah and a few peaceful days by the Indian Ocean in one itinerary.",
"Неделя в мягком ритме: море, древние города и небольшие поездки по западному побережью без ежедневной смены отелей.": "A leisurely week of beaches, ancient towns and short trips along the west coast, without changing hotels every day.",
"Путешествие для двоих с балансом между красивыми островными маршрутами и свободными днями, когда можно никуда не спешить.": "A trip for two, balancing scenic island adventures with unhurried days to yourselves.",
"Осенняя Япония в небольшой группе: насыщенные дни в Токио сменяются более тихим Киото, садами, храмами и клёнами.": "Autumn in Japan with a small group: lively Tokyo followed by Kyoto's peaceful gardens, temples and maple trees.",
"Неспешная Италия с одной красивой базой у моря: Позитано, Амальфи, лимонные сады и время для самостоятельных открытий.": "A relaxed Italian escape with one beautiful seaside base: Positano, Amalfi, lemon groves and time to explore.",
"Тёплый городской уикенд, который постепенно уходит в Кавказ: старые балконы Тбилиси, винные истории и горная дорога к Казбеги.": "A warm city break leading into the Caucasus: Tbilisi's old balconies, wine stories and the mountain road to Kazbegi.",
"Прогулки по Пафосу":"Explore Paphos","Бухты полуострова Акамас":"Akamas Peninsula bays","Свободные дни у моря":"Free days by the sea","Прогулка по островным деревням":"Stroll through island villages","Отдых на побережье":"Coastal relaxation","Греческая кухня и морские закаты":"Greek food and seaside sunsets","Храмы Киото":"Kyoto temples","Прогулка по Арасияме":"Explore Arashiyama","Знакомство с Токио":"Discover Tokyo","Амальфи и Позитано":"Amalfi and Positano","Панорамные дороги побережья":"Scenic coastal roads","Свободный день у моря":"Free day by the sea","Старый Тбилиси":"Old Tbilisi","Казбеги и горные панорамы":"Kazbegi and mountain views",
"Заселение, набережная, старый город и археологический парк с античными мозаиками.":"Check in, explore the waterfront, old town and archaeological park with ancient mosaics.","Морские бухты, природные тропы и день для прогулок по полуострову.":"Discover coastal coves, nature trails and enjoy a day exploring the peninsula.","Свободный ритм, пляж, локальные таверны и финальный вечер у моря.":"Free time, beaches, local tavernas and a final evening by the sea.","Прогулка по историческому центру, Акрополь и первый ужин с видом на город.":"Explore the historic center, the Acropolis and enjoy dinner overlooking Athens.","Белые деревни, маленькие бухты и поездки по побережью.":"Whitewashed villages, hidden coves and coastal adventures.","Пляжные дни, локальная кухня, закаты и возвращение через Афины.":"Beach days, local food, sunsets and the return via Athens.","Современные кварталы, рынки, панорамные точки и знакомство с ритмом мегаполиса.":"Modern neighborhoods, markets, viewpoints and the rhythm of the metropolis.","Храмы, сады, квартал Гион и вечерние прогулки среди осенних клёнов.":"Temples, gardens, the Gion district and evening walks among autumn maples.","Бамбуковая роща, свободный день для покупок и возвращение домой.":"Bamboo grove, a free day for shopping and the journey home.","Прилёт, трансфер к морю и первый вечер с видом на залив.":"Arrival, seaside transfer and your first evening overlooking the bay.","Панорамная дорога, маленькие города, лимонные сады и прогулки у воды.":"Scenic roads, small towns, lemon groves and waterfront strolls.","День для моря или Капри, гастрономический вечер и возвращение домой.":"A day at the sea or on Capri, a foodie evening and the journey home.","Старый город, серные бани, рынки и знакомство с современной грузинской кухней.":"Old town, sulfur baths, markets and modern Georgian cuisine.","Крепость Ананури, горные панорамы, Гудаури и поездка к Казбеги.":"Ananuri Fortress, mountain views, Gudauri and a journey to Kazbegi.","Небольшая дегустация, время для города и возвращение в Тель-Авив.":"A small wine tasting, time in the city and the return to Tel Aviv.",
"Перелёт из Тель-Авива":"Flight from Tel Aviv","7 ночей в бутик-отеле 4★":"7 nights in a 4★ boutique hotel","Завтраки":"Breakfasts","Трансфер аэропорт — отель":"Airport–hotel transfer","Экскурсия по Пафосу":"Paphos guided tour","Поездка на полуостров Акамас":"Akamas Peninsula excursion","Перелёты по маршруту":"Flights on the itinerary","8 ночей в отеле 5★":"8 nights in a 5★ hotel","Трансферы":"Transfers","Обзорная прогулка в Афинах":"Athens walking tour","Один островной маршрут":"One island excursion","Международный перелёт":"International flight","9 ночей в отелях 4★":"9 nights in 4★ hotels","Переезды между городами":"Intercity transport","Экскурсии по Токио и Киото":"Tokyo and Kyoto guided tours","Сопровождение по маршруту":"Tour escort","7 ночей в отеле 4★":"7 nights in a 4★ hotel","Аэропортовые трансферы":"Airport transfers","Поездка Амальфи — Позитано":"Amalfi–Positano excursion","Гастрономический вечер":"Foodie evening","Прямой перелёт":"Direct flight","6 ночей в бутик-отеле 4★":"6 nights in a 4★ boutique hotel","Экскурсия по Тбилиси":"Tbilisi guided tour","Поездка в Казбеги":"Kazbegi excursion",
"Вылет из Тель-Авива; перелёт в Найроби с пересадкой. Перед поездкой требуется электронное разрешение eTA для Кении.":"Depart Tel Aviv for Nairobi with a connection. A Kenya eTA is required before travel.",
"Вылет из Тель-Авива, прямой рейс до Ларнаки. Для краткой туристической поездки по израильскому паспорту виза не требуется.":"Depart Tel Aviv on a direct flight to Larnaca. Israeli passport holders generally do not need a visa for a short tourist visit.",
"Вылет из Тель-Авива в Афины прямым рейсом; дальше — внутренний перелёт или паром в зависимости от выбранного острова. Для короткой поездки в Шенген по израильскому паспорту виза не требуется.":"Fly directly from Tel Aviv to Athens, then take a domestic flight or ferry depending on the island. Israeli passport holders generally do not need a visa for short Schengen visits.",
"Вылет из Тель-Авива. Прямые рейсы в Токио бывают ограниченно; маршрут и наличие мест уточняются перед бронированием. Краткосрочная поездка по израильскому паспорту без визы.":"Depart Tel Aviv. Direct Tokyo flights may be limited; confirm routes and availability before booking. Israeli passport holders generally do not need a visa for a short stay.",
"Вылет из Тель-Авива в Италию прямым рейсом; к побережью — трансфер или внутренний перелёт. Краткосрочная поездка в Шенген по израильскому паспорту без визы.":"Fly from Tel Aviv to Italy, then transfer or connect to the coast. Israeli passport holders generally do not need a visa for short Schengen visits.",
"Вылет из Тель-Авива в Тбилиси прямым рейсом. Перед поездкой проверяются актуальные требования к документам и страховке.":"Fly directly from Tel Aviv to Tbilisi. Check current document and insurance requirements before traveling."
});

/** Translate known copy; leave proper nouns and unrecognized text unchanged. */
export function translateCopy(value: string): string {
  const raw = value.trim();
  const trimmed = raw.replace(/\s+/g, " ");
  if (!trimmed) return value;
  // React renders interpolated headings as separate text nodes. Translate their
  // standalone suffixes as well as complete phrases.
  const dynamicFragments: Record<string, string> = {
    "в своём ритме": "at your own pace",
    "Открыть тур:": "Open tour:",
    "· сентябрь · групповой тур": "· September · group tour",
    "· май · группа из 8 человек": "· May · group of 8",
    "· индивидуальный тур": "· private trip",
    "чел.": "person",
  };
  if (dynamicFragments[trimmed]) return value.replace(raw, dynamicFragments[trimmed]);
  const translated = EN[trimmed] ?? (trimmed.includes(": ") && trimmed.split(": ").length === 2
    ? trimmed.split(": ").map((part) => EN[part] ?? part).join(": ")
    : trimmed)
    .replace(/^(Кения|Кипр|Греция|Япония|Италия|Грузия) в своём ритме$/, (_, country: string) => `${EN[country]} at your own pace`)
    .replace(/^([А-Яа-яЁё]+) 2026$/, (_, month: string) => `${EN[month] ?? month} 2026`);
  return value.replace(raw, translated);
}
