/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as ToursKenyaRouteImport } from './routes/tours.kenya'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursKenyaRoute = ToursKenyaRouteImport.update({
  id: '/tours/kenya',
  path: '/tours/kenya',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/kenya': typeof ToursKenyaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/kenya': typeof ToursKenyaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/kenya': typeof ToursKenyaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tours/$slug' | '/tours/kenya'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tours/$slug' | '/tours/kenya'
  id: '__root__' | '/' | '/tours/$slug' | '/tours/kenya'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToursSlugRoute: typeof ToursSlugRoute
  ToursKenyaRoute: typeof ToursKenyaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/kenya': {
      id: '/tours/kenya'
      path: '/tours/kenya'
      fullPath: '/tours/kenya'
      preLoaderRoute: typeof ToursKenyaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToursSlugRoute: ToursSlugRoute,
  ToursKenyaRoute: ToursKenyaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
